/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonBack: typeof import('./src/components/Buttons/ButtonBack.vue')['default']
    ButtonNext: typeof import('./src/components/Buttons/ButtonNext.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Loader: typeof import('./src/components/Loader/Loader.vue')['default']
    Option: typeof import('./src/components/Select/Option.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/Select/SelectBox.vue')['default']
    SelectOptions: typeof import('./src/components/Select/SelectOptions.vue')['default']
    SelectTrigger: typeof import('./src/components/Select/SelectTrigger.vue')['default']
    WalletCard: typeof import('./src/components/WalletCard.vue')['default']
  }
}
