/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChooseSeed: typeof import('./src/components/ChooseSeed.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    InputSeed: typeof import('./src/components/InputSeed.vue')['default']
    Loader: typeof import('./src/components/Loader/Loader.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletCard: typeof import('./src/components/WalletCard.vue')['default']
  }
}
